server:
  servlet:
    context-path: /openapi/dev
  port: 8081

spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  config:
    activate.on-profile: loan-schedule-inq
    name:  loan-schedule-inq-YAML
  jms:
    useAsyncSend: true
  activemq:
    #    broker-url: tcp://danamon-new-broker-hdls-svc.danamon-new-broker.svc.cluster.local:61616?jms.userName=admin&jms.password=P@ssw0rd
    broker-url: tcp://localhost:61616?jms.userName=admin&jms.password=admin
    concurrency: 3-10
    timeout: 10000
  audit-datasource:
    url: jdbc:oracle:thin:@//10.195.53.8:1521/FCRUAT
    username: ncbsngi
    password: ngi_12345
    schema: ncbsngi
    driver-class-name: oracle.jdbc.driver.OracleDriver
    type: org.apache.tomcat.jdbc.pool.DataSource
    tomcat:
      max-wait: 20000
      max-active: 300
      max-idle: 10
      min-idle: 5
      initial-size: 2
      test-on-connect: true
      test-on-borrow: true
      validation-query: SELECT 1 FROM DUAL
      validation-query-timeout: 10
      validation-interval: 15000
      remove-abandoned: false
      remove-abandoned-timeout: 30
      jmx-enabled: true
  main-datasource:
    url: jdbc:oracle:thin:@//10.195.53.8:1521/FCRUAT
    username: fcr24
    password: ENC(iYWxpqbPzkZUQyPB+pE7DYuX+ind2X+b)
    schema: fcr24
    driver-class-name: oracle.jdbc.driver.OracleDriver
    type: org.apache.tomcat.jdbc.pool.DataSource
    tomcat:
      max-wait: 20000
      max-active: 300
      max-idle: 10
      min-idle: 5
      initial-size: 2
      test-on-connect: true
      test-on-borrow: true
      validation-query: SELECT 1 FROM DUAL
      validation-query-timeout: 10
      validation-interval: 15000
      remove-abandoned: false
      remove-abandoned-timeout: 30
      jmx-enabled: true

  jpa:
    timeout-sec: 30
    generate-ddl: false
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        #        default_schema: ngi
        default_schema: fcr24
  jackson:
    serialization:
      write-dates-as-timestamps: false



logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [${spring.zipkin.service.name:${spring.application.name:-}},%X{traceId:-},%X{spanId:-}] [%t] %-5level %logger{36} - %msg%n"
  level:
    web: WARN
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: DEBUG
      springframework:
        web: TRACE
      apache.tomcat.jdbc.pool: debug


rest:
  config:
    timeout-millis: 30000

---
environment: dev
---

jasypt:
  encryptor:
    password: sdnk#sdjfk@
    algorithm: PBEWithMD5AndDES

log:
  rest-base-url: http://localhost:8012/openapi/dev
  audit:
    type: database # database, rest, or jms
    designation-name: ngi-audit-log-queue
  interface:
    type: database # database, rest, or jms
    designation-name: ngi-interface-log-queue
  sequence-name:
  trace-id-prefix: lnschinq


# Actuators properties
management:
  health:
    circuitbreakers:
      enabled: true
    jms:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*' # ["metrics", "prometheus", "circuitbreakers", "circuitbreakerevents"]
  endpoint:
    health:
      show-details: always

# resilience4j properties
resilience4j:
  circuitbreaker:
    instances:
      loan-schedule-inq:
        registerHealthIndicator: true
        event-consumer-buffer-size: 10
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 3s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true

fcrMakerId: LNOPER014
